# !/bin/sh

# cleanup
rm -rf obj_dir
rm -f lfsr7.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace lfsr7.sv --exe lfsr_tb7.cpp

#build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vlfsr7.mk Vlfsr7

# run executable simulation file
obj_dir/Vlfsr7